### ISSUE TITLE
Confusing argument 'without_pretrain'

### ISSUE THREAD

**Issue by shengwubin** [blueocean92/deep_constrained_clustering#2]
I notice that in experiments/run_DCC_pairwise.py, the arguments without_kmeans and without_pretrain both have action 'store_false', and that means their default values are True. However, if you use without_***, then the condition should be 
```
if not args.without_pretrain:
    idec.load_model(args.pretrain)
```

**Comment by blueocean92** [comment]
Thanks for your interest in our project. If you want to run the pairwise constrained clustering without pre-trained weights you can use the command "python run_DCC_pairwise.py --without_pretrain" with current code.
